services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - cinemaabyss-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - cinemaabyss-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - cinemaabyss-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8085:8080"
    networks:
      - cinemaabyss-network

  monolith:
    build:
      context: ./src/monolith
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - cinemaabyss-network

  movies-service:
    build:
      context: ./src/microservices/movies
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - cinemaabyss-network

  events-service:
    build:
      context: ./src/microservices/events
    depends_on:
      kafka:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - cinemaabyss-network

  proxy-service:
    build:
      context: ./src/microservices/proxy
    depends_on:
      - monolith
      - movies-service
      - events-service
    ports:
      - "8000:8000"
    networks:
      - cinemaabyss-network

  # Оставляем для локального запуска тестов через compose (в CI тесты идут на хосте)
  api-tests:
    build:
      context: ./tests/postman
      dockerfile: Dockerfile
    depends_on:
      monolith:
        condition: service_started
      movies-service:
        condition: service_started
      events-service:
        condition: service_started
      proxy-service:
        condition: service_started
    networks:
      - cinemaabyss-network

networks:
  cinemaabyss-network:
    driver: bridge
