name: Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with docker-compose
        run: docker compose up -d

      - name: Wait for monolith service
        run: |
          echo "Waiting for monolith..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/health > /dev/null; then
              echo "Monolith is up!"
              exit 0
            fi
            sleep 5
          done
          echo "Monolith failed to start"
          exit 1

      - name: Wait for movies service
        run: |
          echo "Waiting for movies-service..."
          for i in {1..30}; do
            if curl -s http://localhost:8081/api/movies/health > /dev/null; then
              echo "Movies service is up!"
              exit 0
            fi
            sleep 5
          done
          echo "Movies service failed to start"
          exit 1

      - name: Wait for events service
        run: |
          echo "Waiting for events-service..."
          for i in {1..30}; do
            if curl -s http://localhost:8082/api/events/health > /dev/null; then
              echo "Events service is up!"
              exit 0
            fi
            sleep 5
          done
          echo "Events service failed to start"
          exit 1

      - name: Wait for proxy service
        run: |
          echo "Waiting for proxy-service..."
          for i in {1..30}; do
            if curl -s http://localhost:8083/api/health > /dev/null; then
              echo "Proxy service is up!"
              exit 0
            fi
            sleep 5
          done
          echo "Proxy service failed to start"
          exit 1

      - name: Build API tests image
        run: docker build -t cinemaabyss-api-tests -f Dockerfile .

      - name: Run API tests
        run: docker run --network=cinemaabyss-network -v "$(pwd)/reports:/app/reports" cinemaabyss-api-tests

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports
