version: "3.8"

services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - monolith
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 15
      start_period: 10s
    networks:
      - cinema

  monolith:
    build: ./monolith
    ports:
      - "5000:5000"
    networks:
      - cinema

  movies:
    build: ./movies
    ports:
      - "5001:5001"
    networks:
      - cinema

  events:
    build: ./events
    ports:
      - "5002:5002"
    networks:
      - cinema

networks:
  cinema:
    name: cinemaabyss-network
