name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'tests/postman/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: tests/postman  # ← ДОБАВЬТЕ ЭТО

      - name: Start services
        run: docker compose up -d --build

      - name: Wait for services to be healthy
        run: |
          for i in {1..30}; do
            # ИСПРАВЛЕННАЯ КОМАНДА:
            if docker compose exec postgres pg_isready -U postgres 2>/dev/null && \
               docker compose ps | grep -q "Up"; then
              echo "All services are healthy!"
              exit 0
            fi
            echo "Waiting for services... ($i/30)"
            sleep 2
          done
          echo "Services failed to become healthy"
          docker compose ps
          exit 1

      - name: Run tests
        run: npm test
        working-directory: tests/postman  # ← ДОБАВЬТЕ ЭТО

      - name: Cleanup
        if: always()
        run: docker compose down
