services:
  monolith:
    build:
      context: ./src/monolith
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - cinema-network

  movies-service:
    build:
      context: ./src/microservices/movies
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - cinema-network

  events-service:
    build:
      context: ./src/microservices/events
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - cinema-network

  proxy-service:
    build:
      context: ./src/microservices/proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONOLITH_URL=http://monolith:3000
      - MOVIES_SERVICE_URL=http://movies-service:3000
      - EVENTS_SERVICE_URL=http://events-service:3000
    depends_on:
      - monolith
      - movies-service
      - events-service
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge
