name: Docker Build, Push and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-build-push.yml'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push proxy-service
      - name: Build and push proxy-service
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/proxy
          file: ./src/microservices/proxy/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/proxy-service:latest

      # Build & Push events-service
      - name: Build and push events-service
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/events
          file: ./src/microservices/events/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/events-service:latest

      # Поднятие сервисов для тестов
      - name: Start services with docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 20
          docker ps -a

      # Установка newman
      - name: Install Newman
        run: npm install -g newman

      # Запуск Postman коллекции
      - name: Run API tests
        run: |
          newman run tests/postman/CinemaAbyss.postman_collection.json \
            --environment tests/postman/local.environment.json \
            --reporters cli
