name: Docker Build, Push and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-build-push.yml'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push proxy-service
      - name: Build and push proxy-service
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/proxy
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/proxy-service:latest
          platforms: linux/amd64

      # Build & Push events-service
      - name: Build and push events-service
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/events
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/events-service:latest
          platforms: linux/amd64

      # Build & Push monolith-service
      - name: Build and push monolith-service
        uses: docker/build-push-action@v4
        with:
          context: ./src/monolith
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/monolith-service:latest
          platforms: linux/amd64

      # Build & Push movies-service
      - name: Build and push movies-service
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/movies
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/movies-service:latest
          platforms: linux/amd64

      # Start services with docker-compose (includes api-tests)
      - name: Start services with docker-compose
        run: |
          docker compose -f docker-compose.yml up -d --build
          sleep 30
          docker ps -a

      # Run API tests inside docker-compose (api-tests service)
      - name: Run API tests
        run: docker compose -f docker-compose.yml run --rm api-tests
