name: Docker Build, Test and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docker-compose.yml'
      - '.github/workflows/docker-build-push.yml'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Собираем образы локально (без пуша)
      - name: Build proxy-service image
        run: docker build -t proxy-service:local ./src/microservices/proxy

      - name: Build events-service image
        run: docker build -t events-service:local ./src/microservices/events

      - name: Save images as artifacts
        run: |
          docker save proxy-service:local -o proxy-service.tar
          docker save events-service:local -o events-service.tar
        shell: bash

      - name: Upload images
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            proxy-service.tar
            events-service.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ima
