jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start services
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          sleep 15

      - name: Build API tests image
        run: |
          docker build -t cinemaabyss-api-tests -f tests/postman/Dockerfile .

      - name: Run API tests
        run: |
          docker run --network=cinemaabyss-network \
            -v "$(pwd)/tests/postman/reports:/app/reports" \
            cinemaabyss-api-tests
